version: '3.3'
services:

  frontend:
    container_name: foodgram-front
    image: sknyazev91/foodgram_frontend:latest
    restart: always
    volumes:
      - ../frontend/:/app/result_build/

  db:
    container_name: foodgram-db
    image: postgres:13.0-alpine
    restart: always
    volumes:
      - /var/lib/postgresql/data/
    env_file:
      - ./.env

  backend:
    container_name: foodgram-app
    image: sknyazev91/foodgram_backend:latest
    restart: always
    volumes:
      - static_dir:/app/static/
      - media_dir:/app/media/
    depends_on:
      - db
    env_file:
      - ./.env

  nginx:
    container_name: foodgram-nginx
    image: nginx:1.19.3
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ../frontend/build:/usr/share/nginx/html/
      - ../docs/:/usr/share/nginx/html/api/docs/
      - static_dir:/etc/nginx/html/static/
      - media_dir:/etc/nginx/html/media/
    depends_on:
      - backend
      - frontend
  
volumes:
  static_dir:
  media_dir:
